import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ViewTransitions } from 'next-view-transitions'
import StoreProvider from "./store-provider";
import { Toaster } from "@/components/ui/toaster";

const publicSans = localFont({
  src: "./fonts/PublicSans-VariableFont_wght.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <StoreProvider>
        <html lang="en">
          <body
            className={`${publicSans.variable} antialiased`}
          >
            {children}
            <Toaster />
          </body>
        </html>
      </StoreProvider>
    </ViewTransitions>
  );
}
